permissions:
  contents: read
name: verify
on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Sanitize npm proxy env (prevents warnings)
        run: |
          npm config delete proxy || true
          npm config delete http-proxy || true
          npm config delete https-proxy || true
          rm -f .npmrc || true

      - name: Install
        run: npm ci --no-audit --prefer-offline

      - name: Doctor
        run: npm run doctor
        continue-on-error: true

      - name: Verify (strict)
        run: npm run verify:strict

      - name: Archive logs/artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            .next/trace
            .next/**/*.html
            .next/**/*.js
            /home/runner/.npm/_logs/*
          if-no-files-found: ignore
